[package]
name = "llama-embd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.11", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4.17"
num_cpus = "1.15.0"
once_cell = "1.17.1"

llama-rs = { path = "../llama-rs" }